
parameters:
    name:  comments   
    title: Комментарии
    css_tab: edit
    parent:
        mainpage: ~
        text: ~     
    count:            1
    count-per-parent: 1
    modules:
        sitetree: FireiceNodeDefault
        frontend: comments 
    type: list