
parameters:
    name:  comments   
    title: Комментарии
    css_tab: edit
    parent:
        mainpage: ~
        text: ~     
    count:            1
    count-per-parent: 1
    modules:
        sitetree: 
          name: FireiceNodeDefault
          multilanguage: no
        frontend: 
          name: comments 
          multilanguage: no
    type: list