
parameters:
    name:  comments   
    title: Комментарии
    css_tab: edit
    parent:
        mainpage: ~
        text: ~     
    count:            25
    count-per-parent: 25
    modules:
        sitetree: FireiceNodeDefault
        frontend: comments 
    type: list