
parameters:
    name:  news   
    title: Новости
    css_tab: edit    
    parent:
        mainpage: ~
        text: ~ 
        news: ~
    count:            15
    count-per-parent: 15
    modules:
        sitetree: 
          name: FireiceNodeDefault
          multilanguage: no
        frontend: 
          name: News 
          multilanguage: yes
          
    type: list