
parameters:
    name:             mainpage   
    title:            Главная страница
    css_tab:          edit
    parent:           
        ROOT: ~
    count:            1
    count-per-parent: 1
    modules:
        sitetree: FireiceNodeDefault
        frontend: Mainpage
    type: item