
parameters:
    name:             contacts   
    title:            Контакты
    css_tab:          edit
    parent:           
        mainpage: ~
        contacts: ~
    count:            100
    count-per-parent: 50
    modules:
        sitetree: 
          name: FireiceNodeDefault
          multilanguage: yes
        frontend: 
          name: Contacts
          multilanguage: yes
    type: item   
