index:
    pattern:  /index
    defaults: { _controller: FireiceModulesTextBundle:Backend:index }

add:
    pattern:  /add
    defaults: { _controller: FireiceModulesTextBundle:Backend:add }
    requirements:
        _method:  GET

doadd:
    pattern:  /add
    defaults: { _controller: FireiceModulesTextBundle:Backend:doAdd }
    requirements:
        _method:  POST

edit:
    pattern:  /edit
    defaults: { _controller: FireiceModulesTextBundle:Backend:edit }
    requirements:
        _method:  GET

doedit:
    pattern:  /edit
    defaults: { _controller: FireiceModulesTextBundle:Backend:doEdit }
    requirements:
        _method:  POST

del:
    pattern:  /del
    defaults: { _controller: FireiceModulesTextBundle:Backend:del }