
parameters:
    name:             contacts   
    title:            Контакты
    parent:           
        mainpage: ~
        contacts: ~
    count:            100
    count-per-parent: 50
    modules:
        sitetree: FireiceModuleSiteTreeNodeOtherBundle
        frontend: ModuleContactsBundle
    type: item