
parameters:
    name:  mails   
    title: Письма
    css_tab: edit
    parent:
        mainpage: ~
        text: ~ 
        news: ~
    count:            15
    count-per-parent: 15
    modules:
        sitetree: FireiceNodeDefault
        frontend: mails 
    type: list