
parameters:
    name:  text   
    title: Текст
    css_tab: edit    
    parent:
        mainpage: ~
        text: ~     
    count:            25
    count-per-parent: 25
    modules:
        sitetree: 
          name: FireiceNodeDefault
          multilanguage: no
        frontend: 
          name: Text 
          multilanguage: yes
    type: item