
parameters:
    name:  text   
    title: Текст
    css_tab: edit    
    parent:
        mainpage: ~
        text: ~     
    count:            25
    count-per-parent: 25
    modules:
        sitetree: FireiceNodeDefault
        frontend: Text 
    type: item