
parameters:
    name:  text   
    title: Текст
    css_tab: edit    
    parent:
        mainpage: ~
        text: ~     
    count:            25
    count-per-parent: 25
    modules:
        sitetree: 
          name: FireiceNodeDefault
          multilanguage: yes
        frontend: 
          name: Text 
          multilanguage: yes
        frontend2: 
          name: News 
          multilanguage: yes
        #frontend3: 
         # name: Mails
         # multilanguage: yes
    type: item