
parameters:
    name:             FireiceNodeOther   
    title:            Настройки
    css_tab:          settings    
    parent:           
        mainpage: ~
        contacts: ~
    count:            100
    count-per-parent: 50
    type: item